apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-kubernetes-hello-world-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  backend:
    serviceName: hello-kubernetes-hello-kubernetes
    servicePort: 80
  rules:
    - host: hello-kubernetes-hello-world.20.40.240.229.nip.io
      http:
        paths:
          - path: /app/hello-kubernetes/
            backend:
              serviceName: hello-kubernetes-hello-world
              servicePort: 80
